import { Select } from 'antd';
import React, { useState } from 'react';
import qs from 'query-string';
import { SearchOutlined } from '@ant-design/icons';
import { useDebounceFn } from 'ahooks';
import { CustomControl } from '../CustomControl';
import type { LocationSearchProps, LocationSearchOption } from './types';
import { CLS_PREFIX } from './constant';
import './index.less';

const { Option } = Select;

export const LocationSearch: React.FC<LocationSearchProps> = ({ position, className, style, gaodeKey }) => {
  // const [searchText, setSearchText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [options, setOptions] = useState<LocationSearchOption[]>([
    {
      id: 'B0GKN4522Z',
      parent: [],
      childtype: [],
      name: '蚂蚁集团A空间',
      type: '公司企业;公司;公司',
      typecode: '170200',
      biz_type: [],
      address: '西溪路569号',
      location: '120.104735,30.261121',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '0',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [
        {
          title: [],
          url: 'http://store.is.autonavi.com/showpic/7902ad9244533c2658c35edeff1b270e',
        },
        {
          title: [],
          url: 'http://aos-cdn-image.amap.com/sns/ugccomment/fc75028b-f558-4950-8249-109444a5694f.jpg',
        },
        {
          title: [],
          url: 'http://aos-cdn-image.amap.com/sns/ugccomment/abe5cb71-aa53-4e18-9e43-6ffcf065c1a9.jpg',
        },
      ],
    },
    {
      id: 'B0HUUHQK30',
      parent: 'B0GKN4522Z',
      childtype: '305',
      name: '蚂蚁A空间(接送客平台访客区)',
      type: '交通设施服务;停车场;专用停车场',
      typecode: '150905',
      biz_type: [],
      address: '西溪路569号',
      location: '120.103583,30.261521',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      parking_type: '地下',
      photos: [],
    },
    {
      id: 'B0HUUHSQ1M',
      parent: 'B0GKN4522Z',
      childtype: '305',
      name: '蚂蚁A空间(接送客平台员工区)',
      type: '交通设施服务;停车场;专用停车场',
      typecode: '150905',
      biz_type: [],
      address: '西溪路569号',
      location: '120.104085,30.261316',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      parking_type: '地下',
      photos: [],
    },
    {
      id: 'B0HD35PC7Q',
      parent: 'B0GKN4522Z',
      childtype: '101',
      name: '蚂蚁A空间(3号门)',
      type: '通行设施;临街院门;临街院门',
      typecode: '991400',
      biz_type: [],
      address: '西溪路569号(古墩路地铁站B口步行460米)',
      location: '120.102758,30.261719',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HGCLIRF3',
      parent: 'B0GKN4522Z',
      childtype: '101',
      name: '蚂蚁A空间(东门)',
      type: '通行设施;临街院门;临街院门',
      typecode: '991400',
      biz_type: [],
      address: '西溪路569号',
      location: '120.104785,30.262946',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [
        {
          title: [],
          url: 'http://store.is.autonavi.com/showpic/9b647ea0352b931267b33f2cbbcd89a6',
        },
      ],
    },
    {
      id: 'B0HRVDUGQC',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(1号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.104163,30.262229',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HR57AH0P',
      parent: 'B0GKN4522Z',
      childtype: '101',
      name: '蚂蚁集团A空间(2号门)',
      type: '通行设施;临街院门;临街院门',
      typecode: '991400',
      biz_type: [],
      address: '西溪路569号',
      location: '120.103582,30.262252',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HRVDTU28',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(4号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.104515,30.261669',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HRVDUOEO',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(3号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.103586,30.260670',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HRVDTM81',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(7号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.105267,30.260988',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HRVDSRQU',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(2号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.103742,30.261534',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HRVDSRQV',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(5号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.104914,30.261302',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HRVDTU29',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(8号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.105841,30.260838',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HKADJQYA',
      parent: 'B0GKN4522Z',
      childtype: '305',
      name: '蚂蚁集团A空间停车场',
      type: '交通设施服务;停车场;公共停车场',
      typecode: '150904',
      biz_type: [],
      address: '西溪路与古墩路交叉口东南60米',
      location: '120.103100,30.261342',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      parking_type: '地面',
      photos: [],
    },
    {
      id: 'B0HKADJYUC',
      parent: 'B0GKN4522Z',
      childtype: '305',
      name: '蚂蚁集团A空间地下停车场',
      type: '交通设施服务;停车场;公共停车场',
      typecode: '150904',
      biz_type: [],
      address: '西溪路与古墩路交叉口东南100米',
      location: '120.103234,30.261122',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      parking_type: '地下',
      photos: [],
    },
    {
      id: 'B0HRVDTEH6',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(9号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.106233,30.260623',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0HRVDT6WP',
      parent: 'B0GKN4522Z',
      childtype: '308',
      name: '蚂蚁A空间(6号楼)',
      type: '地名地址信息;门牌信息;楼栋号',
      typecode: '190403',
      biz_type: [],
      address: '西溪路569号',
      location: '120.104095,30.260537',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '西湖区',
      importance: [],
      shopid: [],
      shopinfo: '2',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: [],
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0FFMB51EM',
      parent: 'B0FFH5OGV3',
      childtype: '202',
      name: '杭州A8空间极简定制(中南国际商城店)',
      type: '购物服务;家居建材市场;家居建材市场',
      typecode: '060600',
      biz_type: [],
      address: '江南大道1088号中南国际大厦15层',
      location: '120.191854,30.197303',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '滨江区',
      importance: [],
      shopid: [],
      shopinfo: '0',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: '3.1',
        cost: [],
      },
      photos: [],
    },
    {
      id: 'B0FFLANCXM',
      parent: 'B0FFH5OGV3',
      childtype: '202',
      name: '第六空间美克A.R.T(中南国际商城店)',
      type: '购物服务;家电电子卖场;家电电子卖场|购物服务;家居建材市场;家居建材市场',
      typecode: '060300|060600',
      biz_type: [],
      address: '江南大道1088号(长河地铁站C口步行360米)',
      location: '120.189997,30.196525',
      tel: [],
      pname: '浙江省',
      cityname: '杭州市',
      adname: '滨江区',
      importance: [],
      shopid: [],
      shopinfo: '0',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: '4.1',
        cost: [],
      },
      photos: [
        {
          title: [],
          url: 'http://store.is.autonavi.com/showpic/cc2d1b9493d2d65f48e73908d0057c33',
        },
      ],
    },
    {
      id: 'B0FFHK0LWM',
      parent: 'B0FFG6KZWP',
      childtype: '202',
      name: '硬趣空间(丰元国际A座店)',
      type: '购物服务;购物相关场所;购物相关场所',
      typecode: '060000',
      biz_type: [],
      address: '丰潭路430号丰元国际大厦A座B1',
      location: '120.106460,30.301077',
      tel: '0571-88189178',
      pname: '浙江省',
      cityname: '杭州市',
      adname: '拱墅区',
      importance: [],
      shopid: [],
      shopinfo: '0',
      poiweight: [],
      distance: [],
      biz_ext: {
        rating: '4.7',
        cost: [],
      },
      photos: [
        {
          title: [],
          url: 'http://store.is.autonavi.com/showpic/23075eaef99530b31d81f6562e7f2422',
        },
        {
          title: [],
          url: 'http://store.is.autonavi.com/showpic/257a544b446c990ad42d85a1ff5fe04f',
        },
        {
          title: [],
          url: 'http://store.is.autonavi.com/showpic/7206bd36474a514748c048f1450510dd',
        },
      ],
    },
  ]);

  const { run: onSearch } = useDebounceFn(
    async (searchText: string) => {
      if (!searchText) {
        // setOptions([]);
        return;
      }
      setIsLoading(true);
      const url = qs.stringifyUrl({
        url: 'https://restapi.amap.com/v3/place/text',
        query: {
          key: gaodeKey,
          keywords: searchText,
        },
      });
      const res = await (await fetch(url)).json().finally(() => {
        setIsLoading(false);
      });
      if (res.status === '1') {
        // setOptions(res.pois ?? []);
      }
    },
    {
      wait: 2000,
    },
  );

  return (
    <CustomControl name="LocationSearch" position={position} className={className} style={style}>
      <Select
        placeholder="请输入要搜索的位置"
        className={`${CLS_PREFIX}_select`}
        showSearch
        allowClear
        loading={isLoading}
        suffixIcon={<SearchOutlined />}
        onSearch={onSearch}
      >
        {options.map((option) => {
          return (
            <Option key={option.id} value={option.id}>
              {option.name}
            </Option>
          );
        })}
      </Select>
    </CustomControl>
  );
};
